### ISSUE TITLE
Keep brightness when changing theme

### ISSUE THREAD

**Issue by Emile86** [DevelopArtist/Homey-McLighting-ledstrip#1]
First of all thank you for nice integration with homey
 
I found a small bug? When i set brightness for example to 100% and then change a theme then leds dimming to very low level but brightness level in the app is still 100%, to bring it back i need to change it to low and then back to high.

**Comment by DevelopArtist** [comment]
Thank you!

Sorry for my very late response. This issue should be fixed in release v1.2.0
